package main

import (
	"flag"
	"fmt"
	"strings"
	"unicode"

	"github.com/dizzrt/ellie/errors"
	"golang.org/x/text/cases"
	"golang.org/x/text/language"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/pluginpb"
)

const (
	release = "v1.1.2"

	// packages
	errorsPackage = protogen.GoImportPath("github.com/dizzrt/ellie/errors")
	codesPackage  = protogen.GoImportPath("google.golang.org/grpc/codes")
)

var showVersion = flag.Bool("version", false, "print the version and exit")

func main() {
	flag.Parse()
	if *showVersion {
		fmt.Printf("protoc-gen-ellie-go-errors %s\n", release)
		return
	}

	var flags flag.FlagSet
	protogen.Options{
		ParamFunc: flags.Set,
	}.Run(func(p *protogen.Plugin) error {
		p.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

		for _, f := range p.Files {
			if !f.Generate {
				continue
			}

			handle(p, f)
		}

		return nil
	})

}

func getProtocVersion(p *protogen.Plugin) string {
	v := p.Request.GetCompilerVersion()

	version := fmt.Sprintf("v%d.%d.%d", v.GetMajor(), v.GetMinor(), v.GetPatch())
	if v.GetSuffix() != "" {
		version += "-" + v.GetSuffix()
	}

	return version
}

func handle(p *protogen.Plugin, f *protogen.File) *protogen.GeneratedFile {
	if len(f.Enums) == 0 {
		return nil
	}

	file := f.GeneratedFilenamePrefix + "_errors.pb.go"
	gf := p.NewGeneratedFile(file, f.GoImportPath)
	gf.P("// Code generated by protoc-gen-ellie-go-errors. DO NOT EDIT.")
	gf.P("// versions:")
	gf.P("//  protoc-gen-ellie-go-errors: ", release)
	gf.P("//  protoc: 				    ", getProtocVersion(p))
	gf.P("// source: ", f.Desc.Path())
	gf.P()
	gf.P("package ", f.GoPackageName)
	gf.P()
	gf.QualifiedGoIdent(errorsPackage.Ident(""))
	gf.QualifiedGoIdent(codesPackage.Ident(""))
	generateContent(p, f, gf)

	return gf
}

func generateContent(p *protogen.Plugin, f *protogen.File, gf *protogen.GeneratedFile) {
	if len(f.Enums) == 0 {
		return
	}

	index := 0
	for _, enum := range f.Enums {
		if !generateErrorsReason(p, f, gf, enum) {
			index++
		}
	}

	if index == 0 {
		gf.Skip()
	}
}

func generateErrorsReason(_ *protogen.Plugin, _ *protogen.File, gf *protogen.GeneratedFile, enum *protogen.Enum) bool {
	defaultCode := 0
	edCode := proto.GetExtension(enum.Desc.Options(), errors.E_DefaultCode)
	if edCode != nil {
		if v, ok := edCode.(int32); ok {
			defaultCode = int(v)
		}
	}

	defaultStatus := errors.ErrorStatus_ERROR_STATUS_UNSPECIFIED
	edStatus := proto.GetExtension(enum.Desc.Options(), errors.E_DefaultStatus)
	if edStatus != nil {
		if v, ok := edStatus.(errors.ErrorStatus); ok {
			defaultStatus = v
		}
	}

	var wrapper errorWrapper
	for _, v := range enum.Values {
		code := defaultCode
		ecode := proto.GetExtension(v.Desc.Options(), errors.E_Code)
		if ok := ecode.(int32); ok != 0 {
			code = int(ok)
		}

		if code == defaultCode {
			continue
		}

		status := defaultStatus
		estatus := proto.GetExtension(v.Desc.Options(), errors.E_Status)
		if estatus != nil {
			if temp, ok := estatus.(errors.ErrorStatus); ok && temp != errors.ErrorStatus_ERROR_STATUS_UNSPECIFIED {
				status = temp
			}
		}

		comment := v.Comments.Leading.String()
		if comment == "" {
			comment = v.Comments.Trailing.String()
		}

		err := &errorInfo{
			Name:       string(enum.Desc.Name()),
			Value:      string(v.Desc.Name()),
			CamelValue: case2Camel(string(v.Desc.Name())),
			Code:       code,
			Status:     int32(status) - 1, // there is a offset 1 between ErrorStatus and grpc.Code
			StatusName: errorStatusName(status),
			Comment:    comment,
			HasComment: len(comment) > 0,
		}
		wrapper.Errors = append(wrapper.Errors, err)
	}

	if len(wrapper.Errors) == 0 {
		return true
	}
	gf.P(wrapper.execute())

	return false
}

var enCases = cases.Title(language.AmericanEnglish, cases.NoLower)

func case2Camel(name string) string {
	if !strings.Contains(name, "_") {
		if name == strings.ToUpper(name) {
			name = strings.ToLower(name)
		}

		return enCases.String(name)
	}

	strs := strings.Split(name, "_")
	words := make([]string, 0, len(strs))
	for _, w := range strs {
		hasLower := false
		for _, r := range w {
			if unicode.IsLower(r) {
				hasLower = true
				break
			}
		}

		if !hasLower {
			w = strings.ToLower(w)
		}
		w = enCases.String(w)
		words = append(words, w)
	}

	return strings.Join(words, "")
}

func errorStatusName(status errors.ErrorStatus) string {
	switch status {
	case errors.ErrorStatus_ERROR_STATUS_UNSPECIFIED:
		return "Unspecified"
	case errors.ErrorStatus_ERROR_STATUS_OK:
		return "Ok"
	case errors.ErrorStatus_ERROR_STATUS_CANCELED:
		return "Canceled"
	case errors.ErrorStatus_ERROR_STATUS_UNKNOWN:
		return "Unknown"
	case errors.ErrorStatus_ERROR_STATUS_INVALID_ARGUMENT:
		return "InvalidArgument"
	case errors.ErrorStatus_ERROR_STATUS_DEADLINE_EXCEEDED:
		return "DeadlineExceeded"
	case errors.ErrorStatus_ERROR_STATUS_NOT_FOUND:
		return "NotFound"
	case errors.ErrorStatus_ERROR_STATUS_ALREADY_EXISTS:
		return "AlreadyExists"
	case errors.ErrorStatus_ERROR_STATUS_PERMISSION_DENIED:
		return "PermissionDenied"
	case errors.ErrorStatus_ERROR_STATUS_RESOURCE_EXHAUSTED:
		return "ResourceExhausted"
	case errors.ErrorStatus_ERROR_STATUS_FAILED_PRECONDITION:
		return "FailedPrecondition"
	case errors.ErrorStatus_ERROR_STATUS_ABORTED:
		return "Aborted"
	case errors.ErrorStatus_ERROR_STATUS_OUT_OF_RANGE:
		return "OutOfRange"
	case errors.ErrorStatus_ERROR_STATUS_UNIMPLEMENTED:
		return "Unimplemented"
	case errors.ErrorStatus_ERROR_STATUS_INTERNAL:
		return "Internal"
	case errors.ErrorStatus_ERROR_STATUS_UNAVAILABLE:
		return "Unavailable"
	case errors.ErrorStatus_ERROR_STATUS_DATA_LOSS:
		return "DataLoss"
	case errors.ErrorStatus_ERROR_STATUS_UNAUTHENTICATED:
		return "Unauthenticated"
	}

	return "Unspecified"
}
