// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.33.0
// source: errors.proto

package errors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// grpc codes.Code
	Status        uint32            `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Code          int32             `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Reason        string            `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Message       string            `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorStatus) Reset() {
	*x = ErrorStatus{}
	mi := &file_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorStatus) ProtoMessage() {}

func (x *ErrorStatus) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorStatus.ProtoReflect.Descriptor instead.
func (*ErrorStatus) Descriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorStatus) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ErrorStatus) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorStatus) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ErrorStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorStatus) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ErrorChainNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Wrapped       *ErrorChainNode        `protobuf:"bytes,4,opt,name=wrapped,proto3" json:"wrapped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorChainNode) Reset() {
	*x = ErrorChainNode{}
	mi := &file_errors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorChainNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorChainNode) ProtoMessage() {}

func (x *ErrorChainNode) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorChainNode.ProtoReflect.Descriptor instead.
func (*ErrorChainNode) Descriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorChainNode) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ErrorChainNode) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorChainNode) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ErrorChainNode) GetWrapped() *ErrorChainNode {
	if x != nil {
		return x.Wrapped
	}
	return nil
}

type ErrorChain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Root          *ErrorChainNode        `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorChain) Reset() {
	*x = ErrorChain{}
	mi := &file_errors_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorChain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorChain) ProtoMessage() {}

func (x *ErrorChain) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorChain.ProtoReflect.Descriptor instead.
func (*ErrorChain) Descriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorChain) GetRoot() *ErrorChainNode {
	if x != nil {
		return x.Root
	}
	return nil
}

var file_errors_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         51001,
		Name:          "errors.default_code",
		Tag:           "varint,51001,opt,name=default_code",
		Filename:      "errors.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         51002,
		Name:          "errors.default_status",
		Tag:           "varint,51002,opt,name=default_status",
		Filename:      "errors.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         52001,
		Name:          "errors.code",
		Tag:           "varint,52001,opt,name=code",
		Filename:      "errors.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         52002,
		Name:          "errors.status",
		Tag:           "varint,52002,opt,name=status",
		Filename:      "errors.proto",
	},
}

// Extension fields to descriptorpb.EnumOptions.
var (
	// optional int32 default_code = 51001;
	E_DefaultCode = &file_errors_proto_extTypes[0]
	// optional uint32 default_status = 51002;
	E_DefaultStatus = &file_errors_proto_extTypes[1]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional int32 code = 52001;
	E_Code = &file_errors_proto_extTypes[2]
	// optional uint32 status = 52002;
	E_Status = &file_errors_proto_extTypes[3]
)

var File_errors_proto protoreflect.FileDescriptor

const file_errors_proto_rawDesc = "" +
	"\n" +
	"\ferrors.proto\x12\x06errors\x1a google/protobuf/descriptor.proto\"\xe7\x01\n" +
	"\vErrorStatus\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12=\n" +
	"\bmetadata\x18\x05 \x03(\v2!.errors.ErrorStatus.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x01\n" +
	"\x0eErrorChainNode\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x120\n" +
	"\awrapped\x18\x04 \x01(\v2\x16.errors.ErrorChainNodeR\awrapped\"8\n" +
	"\n" +
	"ErrorChain\x12*\n" +
	"\x04root\x18\x01 \x01(\v2\x16.errors.ErrorChainNodeR\x04root:A\n" +
	"\fdefault_code\x12\x1c.google.protobuf.EnumOptions\x18\xb9\x8e\x03 \x01(\x05R\vdefaultCode:E\n" +
	"\x0edefault_status\x12\x1c.google.protobuf.EnumOptions\x18\xba\x8e\x03 \x01(\rR\rdefaultStatus:7\n" +
	"\x04code\x12!.google.protobuf.EnumValueOptions\x18\xa1\x96\x03 \x01(\x05R\x04code:;\n" +
	"\x06status\x12!.google.protobuf.EnumValueOptions\x18\xa2\x96\x03 \x01(\rR\x06statusB'Z%github.com/dizzrt/ellie/errors;errorsb\x06proto3"

var (
	file_errors_proto_rawDescOnce sync.Once
	file_errors_proto_rawDescData []byte
)

func file_errors_proto_rawDescGZIP() []byte {
	file_errors_proto_rawDescOnce.Do(func() {
		file_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_errors_proto_rawDesc), len(file_errors_proto_rawDesc)))
	})
	return file_errors_proto_rawDescData
}

var file_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_errors_proto_goTypes = []any{
	(*ErrorStatus)(nil),                   // 0: errors.ErrorStatus
	(*ErrorChainNode)(nil),                // 1: errors.ErrorChainNode
	(*ErrorChain)(nil),                    // 2: errors.ErrorChain
	nil,                                   // 3: errors.ErrorStatus.MetadataEntry
	(*descriptorpb.EnumOptions)(nil),      // 4: google.protobuf.EnumOptions
	(*descriptorpb.EnumValueOptions)(nil), // 5: google.protobuf.EnumValueOptions
}
var file_errors_proto_depIdxs = []int32{
	3, // 0: errors.ErrorStatus.metadata:type_name -> errors.ErrorStatus.MetadataEntry
	1, // 1: errors.ErrorChainNode.wrapped:type_name -> errors.ErrorChainNode
	1, // 2: errors.ErrorChain.root:type_name -> errors.ErrorChainNode
	4, // 3: errors.default_code:extendee -> google.protobuf.EnumOptions
	4, // 4: errors.default_status:extendee -> google.protobuf.EnumOptions
	5, // 5: errors.code:extendee -> google.protobuf.EnumValueOptions
	5, // 6: errors.status:extendee -> google.protobuf.EnumValueOptions
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	3, // [3:7] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_errors_proto_init() }
func file_errors_proto_init() {
	if File_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errors_proto_rawDesc), len(file_errors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_errors_proto_goTypes,
		DependencyIndexes: file_errors_proto_depIdxs,
		MessageInfos:      file_errors_proto_msgTypes,
		ExtensionInfos:    file_errors_proto_extTypes,
	}.Build()
	File_errors_proto = out.File
	file_errors_proto_goTypes = nil
	file_errors_proto_depIdxs = nil
}
