// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.33.2
// source: ellie/errors/status.proto

package errors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorStatus int32

const (
	// fallback to UNKNOWN
	ErrorStatus_ERROR_STATUS_UNSPECIFIED ErrorStatus = 0
	// OK is returned on success.
	ErrorStatus_ERROR_STATUS_OK ErrorStatus = 1
	// Canceled indicates the operation was canceled (typically by the caller).
	//
	// The gRPC framework will generate this error code when cancellation
	// is requested.
	ErrorStatus_ERROR_STATUS_CANCELED ErrorStatus = 2
	// Unknown error. An example of where this error may be returned is
	// if a Status value received from another address space belongs to
	// an error-space that is not known in this address space. Also
	// errors raised by APIs that do not return enough error information
	// may be converted to this error.
	//
	// The gRPC framework will generate this error code in the above two
	// mentioned cases.
	ErrorStatus_ERROR_STATUS_UNKNOWN ErrorStatus = 3
	// InvalidArgument indicates client specified an invalid argument.
	// Note that this differs from FailedPrecondition. It indicates arguments
	// that are problematic regardless of the state of the system
	// (e.g., a malformed file name).
	//
	// This error code will not be generated by the gRPC framework.
	ErrorStatus_ERROR_STATUS_INVALID_ARGUMENT ErrorStatus = 4
	// DeadlineExceeded means operation expired before completion.
	// For operations that change the state of the system, this error may be
	// returned even if the operation has completed successfully. For
	// example, a successful response from a server could have been delayed
	// long enough for the deadline to expire.
	//
	// The gRPC framework will generate this error code when the deadline is
	// exceeded.
	ErrorStatus_ERROR_STATUS_DEADLINE_EXCEEDED ErrorStatus = 5
	// NotFound means some requested entity (e.g., file or directory) was
	// not found.
	//
	// This error code will not be generated by the gRPC framework.
	ErrorStatus_ERROR_STATUS_NOT_FOUND ErrorStatus = 6
	// AlreadyExists means an attempt to create an entity failed because one
	// already exists.
	//
	// This error code will not be generated by the gRPC framework.
	ErrorStatus_ERROR_STATUS_ALREADY_EXISTS ErrorStatus = 7
	// PermissionDenied indicates the caller does not have permission to
	// execute the specified operation. It must not be used for rejections
	// caused by exhausting some resource (use ResourceExhausted
	// instead for those errors). It must not be
	// used if the caller cannot be identified (use Unauthenticated
	// instead for those errors).
	//
	// This error code will not be generated by the gRPC core framework,
	// but expect authentication middleware to use it.
	ErrorStatus_ERROR_STATUS_PERMISSION_DENIED ErrorStatus = 8
	// ResourceExhausted indicates some resource has been exhausted, perhaps
	// a per-user quota, or perhaps the entire file system is out of space.
	//
	// This error code will be generated by the gRPC framework in
	// out-of-memory and server overload situations, or when a message is
	// larger than the configured maximum size.
	ErrorStatus_ERROR_STATUS_RESOURCE_EXHAUSTED ErrorStatus = 9
	// FailedPrecondition indicates operation was rejected because the
	// system is not in a state required for the operation's execution.
	// For example, directory to be deleted may be non-empty, an rmdir
	// operation is applied to a non-directory, etc.
	//
	// A litmus test that may help a service implementor in deciding
	// between FailedPrecondition, Aborted, and Unavailable:
	//
	//	(a) Use Unavailable if the client can retry just the failing call.
	//	(b) Use Aborted if the client should retry at a higher-level
	//	    (e.g., restarting a read-modify-write sequence).
	//	(c) Use FailedPrecondition if the client should not retry until
	//	    the system state has been explicitly fixed. E.g., if an "rmdir"
	//	    fails because the directory is non-empty, FailedPrecondition
	//	    should be returned since the client should not retry unless
	//	    they have first fixed up the directory by deleting files from it.
	//	(d) Use FailedPrecondition if the client performs conditional
	//	    REST Get/Update/Delete on a resource and the resource on the
	//	    server does not match the condition. E.g., conflicting
	//	    read-modify-write on the same resource.
	//
	// This error code will not be generated by the gRPC framework.
	ErrorStatus_ERROR_STATUS_FAILED_PRECONDITION ErrorStatus = 10
	// Aborted indicates the operation was aborted, typically due to a
	// concurrency issue like sequencer check failures, transaction aborts,
	// etc.
	//
	// See litmus test above for deciding between FailedPrecondition,
	// Aborted, and Unavailable.
	//
	// This error code will not be generated by the gRPC framework.
	ErrorStatus_ERROR_STATUS_ABORTED ErrorStatus = 11
	// OutOfRange means operation was attempted past the valid range.
	// E.g., seeking or reading past end of file.
	//
	// Unlike InvalidArgument, this error indicates a problem that may
	// be fixed if the system state changes. For example, a 32-bit file
	// system will generate InvalidArgument if asked to read at an
	// offset that is not in the range [0,2^32-1], but it will generate
	// OutOfRange if asked to read from an offset past the current
	// file size.
	//
	// There is a fair bit of overlap between FailedPrecondition and
	// OutOfRange. We recommend using OutOfRange (the more specific
	// error) when it applies so that callers who are iterating through
	// a space can easily look for an OutOfRange error to detect when
	// they are done.
	//
	// This error code will not be generated by the gRPC framework.
	ErrorStatus_ERROR_STATUS_OUT_OF_RANGE ErrorStatus = 12
	// Unimplemented indicates operation is not implemented or not
	// supported/enabled in this service.
	//
	// This error code will be generated by the gRPC framework. Most
	// commonly, you will see this error code when a method implementation
	// is missing on the server. It can also be generated for unknown
	// compression algorithms or a disagreement as to whether an RPC should
	// be streaming.
	ErrorStatus_ERROR_STATUS_UNIMPLEMENTED ErrorStatus = 13
	// Internal errors. Means some invariants expected by underlying
	// system has been broken. If you see one of these errors,
	// something is very broken.
	//
	// This error code will be generated by the gRPC framework in several
	// internal error conditions.
	ErrorStatus_ERROR_STATUS_INTERNAL ErrorStatus = 14
	// Unavailable indicates the service is currently unavailable.
	// This is a most likely a transient condition and may be corrected
	// by retrying with a backoff. Note that it is not always safe to retry
	// non-idempotent operations.
	//
	// See litmus test above for deciding between FailedPrecondition,
	// Aborted, and Unavailable.
	//
	// This error code will be generated by the gRPC framework during
	// abrupt shutdown of a server process or network connection.
	ErrorStatus_ERROR_STATUS_UNAVAILABLE ErrorStatus = 15
	// DataLoss indicates unrecoverable data loss or corruption.
	//
	// This error code will not be generated by the gRPC framework.
	ErrorStatus_ERROR_STATUS_DATA_LOSS ErrorStatus = 16
	// Unauthenticated indicates the request does not have valid
	// authentication credentials for the operation.
	//
	// The gRPC framework will generate this error code when the
	// authentication metadata is invalid or a Credentials callback fails,
	// but also expect authentication middleware to generate it.
	ErrorStatus_ERROR_STATUS_UNAUTHENTICATED ErrorStatus = 17
)

// Enum value maps for ErrorStatus.
var (
	ErrorStatus_name = map[int32]string{
		0:  "ERROR_STATUS_UNSPECIFIED",
		1:  "ERROR_STATUS_OK",
		2:  "ERROR_STATUS_CANCELED",
		3:  "ERROR_STATUS_UNKNOWN",
		4:  "ERROR_STATUS_INVALID_ARGUMENT",
		5:  "ERROR_STATUS_DEADLINE_EXCEEDED",
		6:  "ERROR_STATUS_NOT_FOUND",
		7:  "ERROR_STATUS_ALREADY_EXISTS",
		8:  "ERROR_STATUS_PERMISSION_DENIED",
		9:  "ERROR_STATUS_RESOURCE_EXHAUSTED",
		10: "ERROR_STATUS_FAILED_PRECONDITION",
		11: "ERROR_STATUS_ABORTED",
		12: "ERROR_STATUS_OUT_OF_RANGE",
		13: "ERROR_STATUS_UNIMPLEMENTED",
		14: "ERROR_STATUS_INTERNAL",
		15: "ERROR_STATUS_UNAVAILABLE",
		16: "ERROR_STATUS_DATA_LOSS",
		17: "ERROR_STATUS_UNAUTHENTICATED",
	}
	ErrorStatus_value = map[string]int32{
		"ERROR_STATUS_UNSPECIFIED":         0,
		"ERROR_STATUS_OK":                  1,
		"ERROR_STATUS_CANCELED":            2,
		"ERROR_STATUS_UNKNOWN":             3,
		"ERROR_STATUS_INVALID_ARGUMENT":    4,
		"ERROR_STATUS_DEADLINE_EXCEEDED":   5,
		"ERROR_STATUS_NOT_FOUND":           6,
		"ERROR_STATUS_ALREADY_EXISTS":      7,
		"ERROR_STATUS_PERMISSION_DENIED":   8,
		"ERROR_STATUS_RESOURCE_EXHAUSTED":  9,
		"ERROR_STATUS_FAILED_PRECONDITION": 10,
		"ERROR_STATUS_ABORTED":             11,
		"ERROR_STATUS_OUT_OF_RANGE":        12,
		"ERROR_STATUS_UNIMPLEMENTED":       13,
		"ERROR_STATUS_INTERNAL":            14,
		"ERROR_STATUS_UNAVAILABLE":         15,
		"ERROR_STATUS_DATA_LOSS":           16,
		"ERROR_STATUS_UNAUTHENTICATED":     17,
	}
)

func (x ErrorStatus) Enum() *ErrorStatus {
	p := new(ErrorStatus)
	*p = x
	return p
}

func (x ErrorStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ellie_errors_status_proto_enumTypes[0].Descriptor()
}

func (ErrorStatus) Type() protoreflect.EnumType {
	return &file_ellie_errors_status_proto_enumTypes[0]
}

func (x ErrorStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorStatus.Descriptor instead.
func (ErrorStatus) EnumDescriptor() ([]byte, []int) {
	return file_ellie_errors_status_proto_rawDescGZIP(), []int{0}
}

var File_ellie_errors_status_proto protoreflect.FileDescriptor

const file_ellie_errors_status_proto_rawDesc = "" +
	"\n" +
	"\x19ellie/errors/status.proto\x12\fellie.errors*\xb8\x04\n" +
	"\vErrorStatus\x12\x1c\n" +
	"\x18ERROR_STATUS_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fERROR_STATUS_OK\x10\x01\x12\x19\n" +
	"\x15ERROR_STATUS_CANCELED\x10\x02\x12\x18\n" +
	"\x14ERROR_STATUS_UNKNOWN\x10\x03\x12!\n" +
	"\x1dERROR_STATUS_INVALID_ARGUMENT\x10\x04\x12\"\n" +
	"\x1eERROR_STATUS_DEADLINE_EXCEEDED\x10\x05\x12\x1a\n" +
	"\x16ERROR_STATUS_NOT_FOUND\x10\x06\x12\x1f\n" +
	"\x1bERROR_STATUS_ALREADY_EXISTS\x10\a\x12\"\n" +
	"\x1eERROR_STATUS_PERMISSION_DENIED\x10\b\x12#\n" +
	"\x1fERROR_STATUS_RESOURCE_EXHAUSTED\x10\t\x12$\n" +
	" ERROR_STATUS_FAILED_PRECONDITION\x10\n" +
	"\x12\x18\n" +
	"\x14ERROR_STATUS_ABORTED\x10\v\x12\x1d\n" +
	"\x19ERROR_STATUS_OUT_OF_RANGE\x10\f\x12\x1e\n" +
	"\x1aERROR_STATUS_UNIMPLEMENTED\x10\r\x12\x19\n" +
	"\x15ERROR_STATUS_INTERNAL\x10\x0e\x12\x1c\n" +
	"\x18ERROR_STATUS_UNAVAILABLE\x10\x0f\x12\x1a\n" +
	"\x16ERROR_STATUS_DATA_LOSS\x10\x10\x12 \n" +
	"\x1cERROR_STATUS_UNAUTHENTICATED\x10\x11B'Z%github.com/dizzrt/ellie/errors;errorsb\x06proto3"

var (
	file_ellie_errors_status_proto_rawDescOnce sync.Once
	file_ellie_errors_status_proto_rawDescData []byte
)

func file_ellie_errors_status_proto_rawDescGZIP() []byte {
	file_ellie_errors_status_proto_rawDescOnce.Do(func() {
		file_ellie_errors_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ellie_errors_status_proto_rawDesc), len(file_ellie_errors_status_proto_rawDesc)))
	})
	return file_ellie_errors_status_proto_rawDescData
}

var file_ellie_errors_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ellie_errors_status_proto_goTypes = []any{
	(ErrorStatus)(0), // 0: ellie.errors.ErrorStatus
}
var file_ellie_errors_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ellie_errors_status_proto_init() }
func file_ellie_errors_status_proto_init() {
	if File_ellie_errors_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ellie_errors_status_proto_rawDesc), len(file_ellie_errors_status_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ellie_errors_status_proto_goTypes,
		DependencyIndexes: file_ellie_errors_status_proto_depIdxs,
		EnumInfos:         file_ellie_errors_status_proto_enumTypes,
	}.Build()
	File_ellie_errors_status_proto = out.File
	file_ellie_errors_status_proto_goTypes = nil
	file_ellie_errors_status_proto_depIdxs = nil
}
