// Code generated by protoc-gen-ellie-go-errors. DO NOT EDIT.
// versions:
//  protoc-gen-ellie-go-errors: v1.0.2
//  protoc: 				    v6.33.0
// source: errdef.proto

package ping

import (
	errors "github.com/dizzrt/ellie/errors"
)

func IsSuccess(err error) bool {
	if err == nil {
		return false
	}
	se := errors.NewStandardErrorFromError(err)
	return se.Reason() == Errors_Success.String() && se.Code() == 100000
}

func Success() *errors.StandardError {
	return errors.NewStandardError(7, 100000, Errors_Success.String(), "")
}

func SuccessWithMsg(format string, args ...interface{}) *errors.StandardError {
	return errors.NewStandardErrorf(7, 100000, Errors_Success.String(), format, args...)
}

func IsInvalidParams(err error) bool {
	if err == nil {
		return false
	}
	se := errors.NewStandardErrorFromError(err)
	return se.Reason() == Errors_InvalidParams.String() && se.Code() == 100001
}

func InvalidParams() *errors.StandardError {
	return errors.NewStandardError(2, 100001, Errors_InvalidParams.String(), "")
}

func InvalidParamsWithMsg(format string, args ...interface{}) *errors.StandardError {
	return errors.NewStandardErrorf(2, 100001, Errors_InvalidParams.String(), format, args...)
}
