// Code generated by protoc-gen-ellie-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-ellie-go-http v1.1.3
// - protoc             v6.32.0
// source: pingv2.proto

package ping

import (
	context "context"
	log "github.com/dizzrt/ellie/log"
	http "github.com/dizzrt/ellie/transport/http"
	ginx "github.com/dizzrt/ellie/transport/http/ginx"
	gin "github.com/gin-gonic/gin"
	otel "go.opentelemetry.io/otel"
	attribute "go.opentelemetry.io/otel/attribute"
	propagation "go.opentelemetry.io/otel/propagation"
	v1_21_0 "go.opentelemetry.io/otel/semconv/v1.21.0"
	trace "go.opentelemetry.io/otel/trace"
)

var _ = new(context.Context)
var _ = new(gin.Engine)
var _ = new(ginx.Ginx)
var _ = new(http.Server)
var _ = otel.Tracer
var _ = new(trace.Span)
var _ = new(log.Logger)
var _ = new(attribute.KeyValue)
var _ = new(propagation.TextMapPropagator)
var _ = v1_21_0.HTTPRequestMethodKey

const TRACER_NAME_PINGV2 = "github.com/dizzrt/ellie/internal/mock/ping"
const OperationPingV2Ping = "/Ping_v2/Ping"

type PingV2HTTPServer interface {
	Ping(context.Context, *PingV2Request) (*PingV2Response, error)
}

func RegisterPingV2HTTPServer(hs *http.Server, srv PingV2HTTPServer) {
	r := hs.Engine()
	r.POST("/v2/ping", _pingv2_PingV2_POST_Ping_HTTP_Handler(hs, srv))
}
func _pingv2_PingV2_POST_Ping_HTTP_Handler(hs *http.Server, srv PingV2HTTPServer) gin.HandlerFunc {
	return func(ctx *gin.Context) {
		var req PingV2Request
		if err := ginx.DecodeRequest(ctx, &req); err != nil {
			ctx.JSON(http.StatusBadRequest, hs.WrapHTTPResponse(nil, err))
			ctx.Abort()
			return
		}

		greq := ctx.Request
		rctx := greq.Context()
		rctx = log.ExtractFromTextMapCarrier(rctx, propagation.HeaderCarrier(greq.Header))
		attributes := []attribute.KeyValue{
			v1_21_0.HTTPRequestMethodKey.String(greq.Method),
			v1_21_0.HTTPRouteKey.String(greq.URL.String()),
			attribute.String("log.id", log.LogIDFromContext(rctx)),
		}

		tracer := otel.Tracer(TRACER_NAME_PINGV2)
		rctx, span := tracer.Start(rctx, "_PingV2_Ping_1_HTTP_Handler",
			trace.WithSpanKind(trace.SpanKindServer),
			trace.WithAttributes(attributes...),
		)
		defer span.End()

		sctx := span.SpanContext()
		rctx = log.WithTraceID(rctx, sctx.TraceID().String())
		rctx = log.WithSpanID(rctx, sctx.SpanID().String())

		res, err := srv.Ping(rctx, &req)
		ctx.Request = ctx.Request.WithContext(rctx)
		if err != nil {
			ctx.JSON(http.HTTPStatusCodeFromError(err), hs.WrapHTTPResponse(res, err))
			ctx.Abort()
			return
		}

		hs.EncodeResponse(ctx, res, err)
	}
}
