// Code generated by protoc-gen-go-ellie-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-ellie-http v1.1.0
// - protoc             v6.32.0
// source: ping.proto

package ping

import (
	context "context"
	http "github.com/dizzrt/ellie/transport/http"
	ginx "github.com/dizzrt/ellie/transport/http/ginx"
	gin "github.com/gin-gonic/gin"
	otel "go.opentelemetry.io/otel"
	trace "go.opentelemetry.io/otel/trace"
)

var _ = new(context.Context)
var _ = new(gin.Engine)
var _ = new(ginx.Ginx)
var _ = new(http.Server)
var _ = otel.Tracer
var _ = new(trace.Span)

const TRACER_NAME = "github.com/dizzrt/ellie/internal/mock/ping"
const OperationPingServiceHello = "/PingService/Hello"
const OperationPingServicePing = "/PingService/Ping"

type PingServiceHTTPServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
}

func RegisterPingServiceHTTPServer(hs *http.Server, srv PingServiceHTTPServer) {
	r := hs.Engine()
	r.GET("/ping", _PingService_Ping_0_HTTP_Handler(hs, srv))
	r.POST("/hello/:name", _PingService_Hello_0_HTTP_Handler(hs, srv))
}
func _PingService_Ping_0_HTTP_Handler(hs *http.Server, srv PingServiceHTTPServer) gin.HandlerFunc {
	return func(ctx *gin.Context) {
		var req PingRequest
		if err := ginx.DecodeRequest(ctx, &req); err != nil {
			ctx.JSON(http.StatusBadRequest, hs.WrapHTTPResponse(nil, err))
			ctx.Abort()
			return
		}

		sctx := ctx.Request.Context()
		tracer := otel.Tracer(TRACER_NAME)
		sctx, span := tracer.Start(sctx, "_PingService_Ping_0_HTTP_Handler",
			trace.WithSpanKind(trace.SpanKindServer),
			trace.WithAttributes(),
		)
		defer span.End()

		res, err := srv.Ping(sctx, &req)
		ctx.Request = ctx.Request.WithContext(sctx)
		if err != nil {
			ctx.JSON(http.HTTPStatusCodeFromError(err), hs.WrapHTTPResponse(res, err))
			ctx.Abort()
			return
		}

		hs.EncodeResponse(ctx, res, err)
	}
}
func _PingService_Hello_0_HTTP_Handler(hs *http.Server, srv PingServiceHTTPServer) gin.HandlerFunc {
	return func(ctx *gin.Context) {
		var req HelloRequest
		if err := ginx.DecodeRequest(ctx, &req); err != nil {
			ctx.JSON(http.StatusBadRequest, hs.WrapHTTPResponse(nil, err))
			ctx.Abort()
			return
		}

		sctx := ctx.Request.Context()
		tracer := otel.Tracer(TRACER_NAME)
		sctx, span := tracer.Start(sctx, "_PingService_Hello_0_HTTP_Handler",
			trace.WithSpanKind(trace.SpanKindServer),
			trace.WithAttributes(),
		)
		defer span.End()

		res, err := srv.Hello(sctx, &req)
		ctx.Request = ctx.Request.WithContext(sctx)
		if err != nil {
			ctx.JSON(http.HTTPStatusCodeFromError(err), hs.WrapHTTPResponse(res, err))
			ctx.Abort()
			return
		}

		hs.EncodeResponse(ctx, res, err)
	}
}
