// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10-devel
// 	protoc        v6.32.0
// source: pingv2.proto

package ping

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingV2Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingV2Request) Reset() {
	*x = PingV2Request{}
	mi := &file_pingv2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingV2Request) ProtoMessage() {}

func (x *PingV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_pingv2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingV2Request.ProtoReflect.Descriptor instead.
func (*PingV2Request) Descriptor() ([]byte, []int) {
	return file_pingv2_proto_rawDescGZIP(), []int{0}
}

func (x *PingV2Request) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingV2Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingV2Response) Reset() {
	*x = PingV2Response{}
	mi := &file_pingv2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingV2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingV2Response) ProtoMessage() {}

func (x *PingV2Response) ProtoReflect() protoreflect.Message {
	mi := &file_pingv2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingV2Response.ProtoReflect.Descriptor instead.
func (*PingV2Response) Descriptor() ([]byte, []int) {
	return file_pingv2_proto_rawDescGZIP(), []int{1}
}

func (x *PingV2Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pingv2_proto protoreflect.FileDescriptor

const file_pingv2_proto_rawDesc = "" +
	"\n" +
	"\fpingv2.proto\x12\x04ping\x1a\x1cgoogle/api/annotations.proto\")\n" +
	"\rPingV2Request\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"*\n" +
	"\x0ePingV2Response\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2P\n" +
	"\x06PingV2\x12F\n" +
	"\x04Ping\x12\x13.ping.PingV2Request\x1a\x14.ping.PingV2Response\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v2/pingB,Z*github.com/dizzrt/ellie/internal/mock/pingb\x06proto3"

var (
	file_pingv2_proto_rawDescOnce sync.Once
	file_pingv2_proto_rawDescData []byte
)

func file_pingv2_proto_rawDescGZIP() []byte {
	file_pingv2_proto_rawDescOnce.Do(func() {
		file_pingv2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pingv2_proto_rawDesc), len(file_pingv2_proto_rawDesc)))
	})
	return file_pingv2_proto_rawDescData
}

var file_pingv2_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pingv2_proto_goTypes = []any{
	(*PingV2Request)(nil),  // 0: ping.PingV2Request
	(*PingV2Response)(nil), // 1: ping.PingV2Response
}
var file_pingv2_proto_depIdxs = []int32{
	0, // 0: ping.PingV2.Ping:input_type -> ping.PingV2Request
	1, // 1: ping.PingV2.Ping:output_type -> ping.PingV2Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pingv2_proto_init() }
func file_pingv2_proto_init() {
	if File_pingv2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pingv2_proto_rawDesc), len(file_pingv2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pingv2_proto_goTypes,
		DependencyIndexes: file_pingv2_proto_depIdxs,
		MessageInfos:      file_pingv2_proto_msgTypes,
	}.Build()
	File_pingv2_proto = out.File
	file_pingv2_proto_goTypes = nil
	file_pingv2_proto_depIdxs = nil
}
