// Code generated by protoc-gen-ellie-go-errors. DO NOT EDIT.
// versions:
//  protoc-gen-ellie-go-errors: v1.1.2
//  protoc: 				    v6.33.2
// source: errdef.proto

package errdef

import (
	errors "github.com/dizzrt/ellie/errors"
	codes "google.golang.org/grpc/codes"
)

func IsSuccess(err error) bool {
	if err == nil {
		return false
	}

	se := errors.NewStandardErrorFromError(err)
	return se.Reason() == Errors_Success.String() && se.Code() == 100000
}

func Success() errors.AdvancedError {
	var status *codes.Code = nil
	status = errors.StatusPtrFromInt(0) // Ok

	return errors.NewStandardError(status, 100000, Errors_Success.String(), "")
}

func IsInvalidParams(err error) bool {
	if err == nil {
		return false
	}

	se := errors.NewStandardErrorFromError(err)
	return se.Reason() == Errors_InvalidParams.String() && se.Code() == 100001
}

func InvalidParams() errors.AdvancedError {
	var status *codes.Code = nil
	status = errors.StatusPtrFromInt(3) // InvalidArgument

	return errors.NewStandardError(status, 100001, Errors_InvalidParams.String(), "")
}

func IsInvalidToken(err error) bool {
	if err == nil {
		return false
	}

	se := errors.NewStandardErrorFromError(err)
	return se.Reason() == Errors_InvalidToken.String() && se.Code() == 100002
}

func InvalidToken() errors.AdvancedError {
	var status *codes.Code = nil

	return errors.NewStandardError(status, 100002, Errors_InvalidToken.String(), "")
}
