// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.33.2
// source: errdef.proto

package errdef

import (
	_ "github.com/dizzrt/ellie/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Errors int32

const (
	Errors_UNKNOWN       Errors = 0
	Errors_Success       Errors = 100000
	Errors_InvalidParams Errors = 100001
	Errors_InvalidToken  Errors = 100002
)

// Enum value maps for Errors.
var (
	Errors_name = map[int32]string{
		0:      "UNKNOWN",
		100000: "Success",
		100001: "InvalidParams",
		100002: "InvalidToken",
	}
	Errors_value = map[string]int32{
		"UNKNOWN":       0,
		"Success":       100000,
		"InvalidParams": 100001,
		"InvalidToken":  100002,
	}
)

func (x Errors) Enum() *Errors {
	p := new(Errors)
	*p = x
	return p
}

func (x Errors) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Errors) Descriptor() protoreflect.EnumDescriptor {
	return file_errdef_proto_enumTypes[0].Descriptor()
}

func (Errors) Type() protoreflect.EnumType {
	return &file_errdef_proto_enumTypes[0]
}

func (x Errors) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Errors.Descriptor instead.
func (Errors) EnumDescriptor() ([]byte, []int) {
	return file_errdef_proto_rawDescGZIP(), []int{0}
}

var File_errdef_proto protoreflect.FileDescriptor

const file_errdef_proto_rawDesc = "" +
	"\n" +
	"\ferrdef.proto\x12\x06errdef\x1a\x19ellie/errors/errors.proto\x1a\x19ellie/errors/status.proto*s\n" +
	"\x06Errors\x12\x11\n" +
	"\aUNKNOWN\x10\x00\x1a\x04\x88\xb2\x19\x00\x12\x19\n" +
	"\aSuccess\x10\xa0\x8d\x06\x1a\n" +
	"\x88\xb2\x19\xa0\x8d\x06\x90\xb2\x19\x01\x12\x1f\n" +
	"\rInvalidParams\x10\xa1\x8d\x06\x1a\n" +
	"\x88\xb2\x19\xa1\x8d\x06\x90\xb2\x19\x04\x12\x1a\n" +
	"\fInvalidToken\x10\xa2\x8d\x06\x1a\x06\x88\xb2\x19\xa2\x8d\x06B5Z3github.com/dizzrt/ellie/internal/mock/errdef;errdefb\x06proto3"

var (
	file_errdef_proto_rawDescOnce sync.Once
	file_errdef_proto_rawDescData []byte
)

func file_errdef_proto_rawDescGZIP() []byte {
	file_errdef_proto_rawDescOnce.Do(func() {
		file_errdef_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_errdef_proto_rawDesc), len(file_errdef_proto_rawDesc)))
	})
	return file_errdef_proto_rawDescData
}

var file_errdef_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_errdef_proto_goTypes = []any{
	(Errors)(0), // 0: errdef.Errors
}
var file_errdef_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_errdef_proto_init() }
func file_errdef_proto_init() {
	if File_errdef_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errdef_proto_rawDesc), len(file_errdef_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errdef_proto_goTypes,
		DependencyIndexes: file_errdef_proto_depIdxs,
		EnumInfos:         file_errdef_proto_enumTypes,
	}.Build()
	File_errdef_proto = out.File
	file_errdef_proto_goTypes = nil
	file_errdef_proto_depIdxs = nil
}
